version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  api: &main_app
    image: stockai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
  celery:
    <<: *main_app
    command: celery -A stockai worker -l info
    
  celery-beat:
    <<: *main_app
    command: celery -A stockai beat -l info
    