version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1